#!/bin/zsh
#kubernetes
alias k='kubectl'
alias kp='kubectl get pods'
alias kn='kubectl get nodes'
alias knc='kubernetes-scaffold'
alias kr='kubectl delete --all pods,services,pvc,pv,configmap,jobs,cronjobs,configmap,replicaset,deployments'
alias ka='kubectl get all'
alias kf='kubectl create -f'
alias krf='kubectl replace -f'
alias ms='minikube start'
alias mr='minikube delete'
alias md='minikube dashboard'
alias mt='minikube tunnel0'
alias ec='f() { openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout "$1" -out "$2" -subj "/CN=$3/O=$3" }'
alias kcc='kubectl cluster-info --context $1'
alias ksc='kubect config use-context $1'
alias ktx='kubectx'
alias kbn='kubens'
alias ktxr='reload-kubectl-contexts'
alias kdp='kubectl run -i --tty --rm lolololol -n $1 --image=alpine:latest --restart=Never -- sh'
alias ket='kubectl events --sort-by=".lastTimestamp" -w'
