---

- name: Copy git standard configs
  ansible.builtin.file:
    src: "{{ ( dotfiles_location, 'files/git/', item) | path_join }}"
    dest: "{{ (home_dir, item) | path_join }}"
    owner: "{{ username }}"
    group: "{{ user_group }}"
    force: "{{ use_force }}"
    mode: "0644"
    state: "link"
  with_items:
    - ".gitattributes"
    - ".gitconfig"
    - ".gitignore"

- name: Copy git custom configs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ (home_dir, item.dest) | path_join }}"
    owner: "{{ username }}"
    group: "{{ user_group }}"
    mode: "0600"
  with_items:
    - src: "gitconfig.j2"
      dest: ".gitconfig-default"
