---

- name: Copy git standard configs
  ansible.builtin.copy:
    src: "git/{{ item }}"
    dest: "{{ home_dir }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ user_group }}"
    mode: "0600"
    follow: true
  with_items:
    - ".gitattributes"
    - ".gitconfig"
    - ".gitignore"

- name: Copy git custom configs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ home_dir }}/{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ user_group }}"
    mode: "0600"
  with_items:
    - src: "gitconfig.j2"
      dest: ".gitconfig-default"
