#!/bin/bash

setup_rbenv()
{
    if [ ! -e ~/.rbenv ]; then
        echo "clonning rbenv"
        git clone https://github.com/rbenv/rbenv.git  "$USERHOME/.rbenv"
        cd ~/.rbenv && src/configure && make -C src
        ~/.rbenv/bin/rbenv init
        # shellcheck disable=SC1090
        source  "$USERHOME/.zshrc"
        curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
    fi
}

print_message "Setup Ruby Dev Environment"
setup_rbenv
