# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# History settings
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
# set options commands
setopt NO_BG_NICE # don't nice background tasks
setopt NO_HUP
setopt NO_LIST_BEEP
setopt LOCAL_OPTIONS # allow functions to have local options
setopt LOCAL_TRAPS # allow functions to have local traps
setopt HIST_VERIFY
setopt SHARE_HISTORY # share history between sessions ???
setopt EXTENDED_HISTORY # add timestamps to history
setopt PROMPT_SUBST
setopt CORRECT
setopt COMPLETE_IN_WORD
setopt IGNORE_EOF
setopt APPEND_HISTORY # adds history
setopt INC_APPEND_HISTORY SHARE_HISTORY  # adds history incrementally and share it across sessions
setopt HIST_IGNORE_ALL_DUPS  # don't record dupes in history
setopt HIST_REDUCE_BLANKS

# UI settings
ZSH_THEME="bira"
# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"
ZSH_CUSTOM=~/.config/zsh
plugins=(git common-aliases docker tmux history python dnf systemd)
source $ZSH/oh-my-zsh.sh
# fix to load snap apps
emulate sh -c '. /etc/profile'
stty -ixon
setxkbmap pt
export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/rubemlrm/.config/composer/vendor/bin:/home/rubemlrm/.local/bin"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

