---
- name: Converge
  hosts: instance
  become: true
  vars_files:
    - test_data/testing.yml
  pre_tasks:
    - name: Add system user
      ansible.builtin.user:
        name: "{{ username }}"
        shell: "/usr/bin/zsh"
        groups: "wheel"
        append: yes
    - name: Created base folders for configs
      ansible.builtin.file:
        path: "{{ home_dir }}/.config"
        state: directory
        mode: 0755
        owner: "{{ username }}"
        group: "{{ user_group }}"
  roles:
    - rubemlrm.dotfiles
