---
- name: Converge
  hosts: instance
  become: true
  vars_files:
    - test_data/testing.yml
  pre_tasks:
    - name: Ensure user groups 
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      with_items:
        - "wheel"
        - "{{ user_group }}"
    - name: Add system user
      ansible.builtin.user:
        name: "{{ username }}"
        group: "{{ user_group }}"
        shell: "/usr/bin/zsh"
    - name: Update repositories cache 
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

  roles:
    - extra_packages
    - git
    - fonts
    - dotfiles
