---
- name: Converge
  hosts: instance
  become: true
  vars_files:
    - test_data/testing.yml
  pre_tasks:
    - name: Update dnf cache
      ansible.builtin.dnf:
        name: "*"
        state: latest # noqa package-latest
      tags:
        - skip_ansible_lint
    - name: Add system user
      ansible.builtin.user:
        name: "{{ username }}"
        shell: "/usr/bin/zsh"
        groups: "wheel"
        append: yes
      no_log: false
  roles:
    - rubemlrm.dotfiles
