---
- name: Install utils
  when: ansible_facts['os_family'] != "Darwin"
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items: '{{ extra_packages_common_packages }}'
  become: true

- name: Install debian family utils
  when: ansible_facts['os_family'] == "Debian"
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items: '{{ extra_packages_debian_family_packages }}'
  become: true

- name: Install Macos base packages
  when:  ansible_facts['os_family'] == "Darwin"
  become: true
  become_user: "{{ username }}"
  block:
    - name: "Install packages"
      community.general.homebrew:
        state: present
        name: "{{ item }}"
      with_items: "{{ extra_packages_macos_packages }}"
