#!/usr/bin/env bash

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"
## Java hack
#wmname LD3D
wmname LG3D

## Configurations --------------------------------------------#
if [[ "$HOSTNAME" == "rmotalaptop" ]]; then
	source "$HOME/.config/bspwm/rmotalaptop-config"
elif [[ "$HOSTNAME" == "DojoDesktop" ]]; then
	source "$HOME/.config/bspwm/dojodesktop-config"
else
	bspc monitor 1 -n "1" -d 1 2 3 4 5 6
fi

workspaces

bspc config border_width 1
bspc config window_gap 1
bspc config split_ratio 0.50

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

## Window rules ----------------------------------------------#
bspc rule -r *:*
setAppsRules

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst xfce4-power-manager xfce4-screensaver blueman-applet redshift flameshot solaar redshift

# Lauch xsettingsd daemon
xsettingsd &
/usr/bin/gnome-keyring-daemon --start --components=ssh,secrets,pkcs11 &

# polkit agent
if [[ ! `pidof /usr/libexec/xfce-polkit` ]]; then
	/usr/libexec/xfce-polkit &
fi
if [[ `pidof picom` ]]; then
	killall picom
fi
picom --config "$HOME/.config/picom.conf" &
feh --bg-scale ~/.config/wallpapers/wall3.jpg &
# Lauch keybindings daemon
sxhkd &
xfce4-power-manager &
thunar --daemon &
blueman-applet &
nm-applet &
megasync &
solaar --window=hide &
flameshot &

# Fix cursor
xsetroot -cursor_name left_ptr

# enable redshitf
redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq -r '"\(.location.lat):\(.location.lng)"') &
if [[ `pidof polybar` ]]; then
 	killall polybar
	setPolybar
else
	setPolybar
fi

setAppsAutoStart
