#!/usr/bin/env bash

export NETWORK_CARD="wlp0s20f3"
export SPECIFIC_TRAYBAR_POLYBAR_MODULES="battery sep"

workspaces() {
    TOTAL_MONITORS=$(bspc query -M | wc -l)
	if [[ $TOTAL_MONITORS -eq "3" ]]; then
        xrandr --output eDP-1 --mode 1920x1200 --pos 777x1080 --rotate normal --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1 --off --output DP-2 --off --output DP-3 --mode 1920x1080 --pos 1962x0 --rotate normal --output DP-4 --off
		# set workspaces splitted by monitors
		bspc monitor  DP-1 -n "DP-1" -d 1 2 3
        bspc monitor  DP-3 -n "DP-3" -d 4 5 6
        bspc monitor  eDP-1 -n "eDP-1" -d 7

	elif [[ $TOTAL_MONITORS -eq "2" ]]; then
		xrandr --output eDP-1 --primary --mode 1920x1200 --pos 1052x2160 --rotate normal --output DP-1 --off --output HDMI-1 --off --output DP-2 --off --output DP-3 --mode 3840x2160 --pos 0x0 --rotate normal --output DP-4 --off
		bspc monitor  eDP-1 -n "eDP-1" -d 6 7 8
		bspc monitor  DP-3 -n "DP-3" -d 1 2 3 4 5
	else
		bspc monitor eDP-1 -n "eDP-1" -d 1 2 3 4 5 6 7
	fi
}

setAppsRules() {
    bspc rule -a "Code - Insiders" desktop="^2"
    bspc rule -a "firefox" desktop="^4"
    bspc rule -a "Google-Chrome" desktop="^4"
    bspc rule -a "terminator" desktop="^3"
    bspc rule -a "whatsapp-desktop-linux" desktop='^5'
    bspc rule -a "Mattermost" desktop="^5"
	bspc rule -a "Slack" desktop='^5'
    bspc rule -a "teams-for-linux" desktop='^6'
    bspc rule -a "discord" desktop='^6'
}

setAppsAutoStart() {
    sleep 10;
    brightnessctl set 75% -q;
    killall -9 alacritty && alacritty
    flatpak run com.mattermost.Desktop &
    flatpak run com.slack.Slack &
    flatpak run io.github.mimbrero.WhatsAppDesktop &
    killall -9 code-insiders && code-insiders &
}

setPolybar() {
    TOTAL_MONITORS=$(bspc query -M | wc -l)
    if [[ $TOTAL_MONITORS -eq "3" ]]; then
        MONITOR="eDP-1" polybar -q main -c "$HOME/.config/polybar/config.ini" &
        MONITOR="DP-1" polybar -q main -c "$HOME/.config/polybar/config.ini" &
        MONITOR="DP-3" polybar -q main -c "$HOME/.config/polybar/config.ini" &
    elif [[ $TOTAL_MONITORS -eq "2" ]]; then
        MONITOR="eDP-1" polybar -q main -c "$HOME/.config/polybar/config.ini" &
        MONITOR="DP-3" polybar -q main -c "$HOME/.config/polybar/config.ini" &
    else
        MONITOR="eDP-1" polybar -q main -c "$HOME/.config/polybar/config.ini" &
    fi
}
